version: '3.8'

services:
  blog-app-backend-dev:
    image: blog-app-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    env_file:
      - ./backend/.env
    container_name: blog-app-backend-dev

  blog-app-frontend-dev:
    image: blog-app-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
     - "5173:5173"
    container_name: blog-app-frontend-dev
